#!/usr/bin/env perl
# Removes v2 chained deprels (over elided nodes) from a CoNLL-U file because the current validator does not permit them.
# Dan Zeman <zeman@ufal.mff.cuni.cz>

my $debug = 0;
while(<>)
{
    if(m/^\d+\t/)
    {
        s/\r?\n$//;
        my @fields = split(/\t/);
        my $edeprel = $fields[7];
        $fields[7] =~ s/>.*//;
        if($edeprel ne $fields[7])
        {
            # Remember the original "enhanced" relation in the MISC column.
            # We will convert it to real enhanced dependencies by UD guidelines for some future release.
            $fields[9] .= "|Edep=$fields[6]:$edeprel";
        }
        # For debugging purposes swap the Arabic and Latin scripts.
        if($debug && $fields[9] =~ m/Translit=(.*?)(\||$)/)
        {
            my $translit = $1;
            $fields[9] .= "|Arabic=$fields[1]";
            $fields[1] = $translit;
        }
        # At present (September 2016) there are no morphological features.
        # The only exception is NumType=Card, which is automatically generated by Treex for every numeral.
        # It is not helpful in this state, so let's remove it.
        $fields[5] = '_';
        $_ = join("\t", @fields)."\n";
    }
    print;
}
